version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: pytest
    versions:
    - 6.2.2
